name: "Manuel Meyer"
description: ""

url: "vikingosegundo.github.io"

paginate: 20

markdown: rdiscount
permalink: pretty
highlighter: rouge

gems: ['jekyll-less']

footer-links:
  stackoverflow: 106435/vikingosegundo
  github: vikingosegundo
  twitter: vikingosegundo
